FROM node:18-alpine

WORKDIR /app

COPY ./package.json ./package-lock.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run-script", "build"]
CMD ["node", ".output/server/index.mjs"]
