FROM golang:1.23 AS builder

WORKDIR /app

COPY . .

RUN go mod tidy

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

# Use a minimal base image for the final image
FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y \
    netcat \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/main .

EXPOSE 8080

CMD bash -c "until nc -z -v -w30 db 3306; do echo 'Waiting for MySQL...'; sleep 5; done; ./main"
